// swift-tools-version: 6.2
import PackageDescription

let package = Package(
    name: "ThorVGPackage",
    platforms: [.iOS(.v26), .macOS(.v26)],
    products: [
        .library(name: "ThorVGCpp", targets: ["ThorVGCpp"]),
    ],
    targets: [
        .target(
            name: "ThorVGCpp",
            path: ".",
            exclude: [
                "test",
                "tools",
                "cross",
                "src/loaders/lottie",
                "src/loaders/svg",
                "src/loaders/png",
                "src/loaders/jpg",
                "src/loaders/webp",
                "src/loaders/external_png",
                "src/loaders/external_jpg",
                "src/loaders/external_webp",
                "src/renderer/gpu_engine",
                "src/renderer/tvgInitializer.cpp",
                "src/savers",
                "meson.build",
                "meson_options.txt",
                "tvg-format.sh",
            ],
            sources: [
                "src/common/tvgColor.cpp",
                "src/common/tvgCompressor.cpp",
                "src/common/tvgMath.cpp",
                "src/common/tvgStr.cpp",
                "src/renderer/tvgAccessor.cpp",
                "src/renderer/tvgAnimation.cpp",
                "src/renderer/tvgCanvas.cpp",
                "src/renderer/tvgFill.cpp",
                "src/renderer/tvgLoaderMgr.cpp",
                "src/renderer/tvgPaint.cpp",
                "src/renderer/tvgPicture.cpp",
                "src/renderer/tvgRender.cpp",
                "src/renderer/tvgSaver.cpp",
                "src/renderer/tvgScene.cpp",
                "src/renderer/tvgShape.cpp",
                "src/renderer/tvgTaskScheduler.cpp",
                "src/renderer/tvgText.cpp",
                "src/renderer/cpu_engine/tvgSwFill.cpp",
                "src/renderer/cpu_engine/tvgSwImage.cpp",
                "src/renderer/cpu_engine/tvgSwMath.cpp",
                "src/renderer/cpu_engine/tvgSwMemPool.cpp",
                "src/renderer/cpu_engine/tvgSwPostEffect.cpp",
                "src/renderer/cpu_engine/tvgSwRaster.cpp",
                "src/renderer/cpu_engine/tvgSwRenderer.cpp",
                "src/renderer/cpu_engine/tvgSwRle.cpp",
                "src/renderer/cpu_engine/tvgSwShape.cpp",
                "src/renderer/cpu_engine/tvgSwStroke.cpp",
                "src/loaders/raw/tvgRawLoader.cpp",
                "src/loaders/ttf/tvgTtfLoader.cpp",
                "src/loaders/ttf/tvgTtfReader.cpp",
                "swift/thorvg_initializer.cpp",
            ],
            publicHeadersPath: "swift/include",
            cxxSettings: [
                .define("TVG_STATIC"),
                .headerSearchPath("swift"),
                .headerSearchPath("inc"),
                .headerSearchPath("src/common"),
                .headerSearchPath("src/renderer"),
                .headerSearchPath("src/renderer/cpu_engine"),
                .headerSearchPath("src/loaders/raw"),
                .headerSearchPath("src/loaders/ttf"),
                .unsafeFlags(["-fno-exceptions", "-fno-rtti", "-w"]),
            ]
        ),
    ],
    cxxLanguageStandard: .cxx17
)
